
000000
1.tldr
2
Exec
Makefile
Parser
TESTER
c_formatter_42
error before execution
k
lafklaf
main.c
minishell
minishell.h
[0]
[5]
[?2004h/Users/youmoukh/Desktop/MiniShell [32m$>[0m 
/Users/youmoukh/Desktop/MiniShell [32m$>[0m echo 
[?2004lfd_out == [1]

YOUNES[0]
[1]
[?2004h/Users/youmoukh/Desktop/MiniShell [32m$>[0m 
[?2004l[?2004h/Users/youmoukh/Desktop/MiniShell [32m$>[0m 
[?2004l[?2004h/Users/youmoukh/Desktop/MiniShell [32m$>[0m 
[?2004l[?2004h/Users/youmoukh/Desktop/MiniShell [32m$>[0m asd
[?2004l[0]
[1]
[?2004h/Users/youmoukh/Desktop/MiniShell [32m$>[0m as
[?2004l
/Users/youmoukh/Desktop/MiniShell [32m$>[0m [0]
[1]
[?2004h/Users/youmoukh/Desktop/MiniShell [32m$>[0m 
[?2004l[?2004h/Users/youmoukh/Desktop/MiniShell [32m$>[0m 
[?2004l[?2004h/Users/youmoukh/Desktop/MiniShell [32m$>[0m 
[?2004l[?2004h/Users/youmoukh/Desktop/MiniShell [32m$>[0m 
[?2004l[?2004h/Users/youmoukh/Desktop/MiniShell [32m$>[0m [?2004l
